[package]
name = "sympathy-setup"
version = "1.0.0"
edition = "2021"
description = "sympathy installer"
license = "LGPL-3.0-or-later"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
winreg = "0.55"
windows = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Storage_Compression",
  "Win32_Storage_FileSystem",
  "Win32_System_Diagnostics_ToolHelp",
  "Win32_System_Threading",
  "Win32_Graphics_Dwm",
] }

[profile.release]
opt-level = "s"
lto = "thin"
codegen-units = 16
incremental = true
strip = true
